config/routes.rb
Rails.application.routes.draw do
  get 'view/degree'

  get 'view/tree'

  get 'courses/index'
  get 'courses/input'
  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end

  def input

  end
  
end

app/controllers/view_controller.rb
class ViewController < ApplicationController
  def degree
  end

  def tree
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def getYearsArray
    years = [[(Date.today - 5.years).year, (Date.today - 5.years).year],
            [(Date.today - 4.years).year, (Date.today - 4.years).year],
            [(Date.today - 3.years).year, (Date.today - 3.years).year],
            [(Date.today - 2.years).year, (Date.today - 2.years).year],
            [(Date.today - 1.years).year, (Date.today - 1.years).year],
            [Date.today.year, Date.today.year],
            [(Date.today + 1.years).year, (Date.today + 1.years).year],
            [(Date.today + 2.years).year, (Date.today + 2.years).year],
            [(Date.today + 3.years).year, (Date.today + 3.years).year],
            [(Date.today + 4.years).year, (Date.today + 4.years).year],
            [(Date.today + 5.years).year, (Date.today + 5.years).year],
            [(Date.today + 6.years).year, (Date.today + 6.years).year]]
  end

  def getTermsArray
    terms = [["Fall", "Fall"],
            ["Winter", "Winter"],
            ["Spring", "Spring"],
            ["Summer", "Summer"]]
  end

end

app/helpers/view_helper.rb
module ViewHelper
end

app/views/courses/_term.html.erb
<fieldset>
  <%= fields_for :courses do |f| %>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <%= f.label :year, "Year:", class: "input-group-text control-label" %>
      </div>
      <%= f.select(:score, options_for_select(getYearsArray, selected: Date.today.year), {}, {class: "custom-select", selected:"Choose..."}) %>

    </div>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <%= f.label :term, "Term:", class: "input-group-text control-label" %>
      </div>
      <%= f.select(:score, options_for_select(getTermsArray), {}, {class: "custom-select"}) %>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course1, "Course 1:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course1, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course2, "Course 2:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course2, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course2, "Course 2:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course2, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course3, "Course 3:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course3, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course4, "Course 4:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course4, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course5, "Course 5:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course5, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course6, "Course 6:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course6, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <%= f.label :course7, "Course 7:", class: "input-group-text control-label" %>
        </div>
        <%= f.text_field :course7, class: "form-control" %>
      </div>
    </div>
  <% end %>
</fieldset>

<hr>
<br>

app/views/courses/index.html.erb
<h1>Advisor Ai</h1>
<hr>



<h2>Get Started Here!</h2>
<%=link_to "Course Input", courses_input_path%>
<% if true %>
  <h2>View Tree View</h2>
  <%= link_to "Degree Tree", view_tree_path %>
  <h2>View Your Courses</h2>
  <%= link_to "Degree Path", view_degree_path %>
<% end %>

<%= react_component("HelloWorld", { greeting: "Hello" }) %>

app/views/courses/input.html.erb
<h1>Course Input</h1>
<br>
<div class="float-right" id="upload">
  <button type="button" class="btn btn-info" id="upload">
    <i class="fas fa-download"></i>
    Import Existing Plan
  </button>
</div>

<br>
<%= form_tag '/view/degree', method: :get do %>
  <div class="terms">
    <div class="row" id="clone0">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text">Year</label>
        </div>
        <%= select_tag 'terms[year][]', options_for_select(getYearsArray, Date.today.year), {class: "custom-select", selected:Date.today.year} %>
      </div>

      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text">Term</label>
        </div>
        <%= select_tag 'terms[term][]', options_for_select(getTermsArray), {class: "custom-select"} %>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 1</span>
          </div>
          <%= text_field_tag 'terms[course1][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 2</span>
          </div>
          <%= text_field_tag 'terms[course2][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 3</span>
          </div>
          <%= text_field_tag 'terms[course3][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 4</span>
          </div>
          <%= text_field_tag 'terms[course4][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 5</span>
          </div>
          <%= text_field_tag 'terms[course5][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 6</span>
          </div>
          <%= text_field_tag 'terms[course6][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group mb-3">
          <div class="input-group-prepend" id="course">
            <span class="input-group-text" id="inputGroup-sizing-default">Course 7</span>
          </div>
          <%= text_field_tag 'terms[course7][]', '', class: "form-control", id: "course-input-field"%>
        </div>
      </div>

      <span class="input-group-btn">
        <button type="button" class="btn btn-success btn-add" id="add-term">
          <span>Add Another Term</span>
        </button>
        <br>
        <br>
      </span>

    </div>
  </div>

  <%= submit_tag 'Submit', class:"btn btn-info" %>

<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">


  <%= link_to "Advisor Ai", root_url, class:"navbar-brand" %>
  <!-- <a class="navbar-brand" href="<% root_url %>">Advisor Ai</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= courses_input_path %>">Import Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= view_degree_path %>">My Degree</a>
      </li>

    </ul>
  </div>
  </div>
</nav>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advisor Ai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag    'application' %>
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
  </head>



  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
    <!-- <hr> -->
    <div class="container">
      <footer class="page-footer  mt-4">
        <br>
      </footer>
    </div>
  </body>


</html>

app/views/view/degree.html.erb
<h1>My Classes</h1>

<div class="float-right" id="upload">
  <button type="button" class="btn btn-info" id="download">
    <i class="fas fa-upload"></i>
    Export Existing Plan
  </button>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#degreeCompletionModal">
  Compare Degree Completion
</button>
<br>
<!-- Modal -->
<div class="modal fade" id="degreeCompletionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Compare Degrees</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>BS Computer Science</h4>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 85%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">85%</div>
        </div>
        <br>
        <h4>BS Software Engineering</h4>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">80%</div>
        </div>
        <br>
        <h4>BS Computer Engineering</h4>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 65%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">65%</div>
        </div>
        <br>
        <h4>Software Engineering Minor</h4>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 45%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">45%</div>
        </div>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">EX20XX</th>
      <th scope="col">Class</th>
      <th scope="col">Title</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>
        <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href="">CS 171</a>
      </td>
      <td>CS 171 Title</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>
        <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href="">CS 265</a>
      </td>
      <td>Physics</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>ENGL 101</td>
      <td>English</td>
    </tr>
  </tbody>
</table>



<% for i in 0..params[:terms][:year].length-1 do %>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"> <%= params[:terms][:term].at(i) %> <%= params[:terms][:year].at(i) %></th>
        <th scope="col">Class</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course1].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">2</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course2].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">3</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course3].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">4</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course4].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">5</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course5].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">6</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course6].at(i) %></a>
          </td>
      </tr>
      <tr>
        <th scope="row">7</th>
          <td>
            <a class="course-more-info" data-toggle="modal" data-target="#courseInfoModal" data-whatever="@mdo" href=""><%= params[:terms][:course7].at(i) %></a>
          </td>
      </tr>
    </tbody>
  </table>
<% end %>


<button type="button" class="btn btn-success">Import Plan</button>
<button type="button" class="btn btn-danger">Export Plan</button>

<br>
<br><br><br><br><br>

<!-- Course info modal -->
<div class="modal fade" id="courseInfoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CS 171</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table">

          <tbody>
            <tr>
              <th scope="row">Course</th>
              <td id="modal-course">-</td>
            </tr>
            <tr>
              <th scope="row">Title</th>
              <td id="modal-title">-</td>
            </tr>
            <tr>
              <th scope="row">Description</th>
              <td id="modal-description">-</td>
            </tr>
            <tr>
              <th scope="row">Restrictions</th>
              <td id="modal-restrictions">-</td>
            </tr>

          </tbody>
        </table>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/view/tree.html.erb
<h1>View#tree</h1>
<p>Find me in app/views/view/tree.html.erb</p>